[project]
name = "get_weather"
version = "0.1.0"
description = "simple weather tool"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "fastmcp>=2.11.0",
    "requests>=2.32.3",
]
