name: Build-Publish

on:
  # Run this workflow on pushes of tags like v1.0.0
  push:
    tags:
    - 'v*'
  # Allows also to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions to write packages
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        image_config:
          - name: a2a_contact_extractor
            path: ./a2a
          - name: a2a_currency_converter
            path: ./a2a
          - name: slack_researcher
            path: ./a2a
          - name: weather_service
            path: ./a2a  
          - name: weather_tool
            path: ./mcp
          - name: slack_tool
            path: ./mcp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata for ${{ matrix.image_config.name }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.image_config.name }}
          tags: |
            # extract tag from git ref, e.g., v1.0.0 -> 1.0.0
            type=ref,event=tag

      - name: Build and push ${{ matrix.image_config.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image_config.path }}/${{ matrix.image_config.name }}
          file: ${{ matrix.image_config.path }}/${{ matrix.image_config.name }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

     